### ISSUE TITLE
Closing the scheduler throws an `asyncio.CancelledError`

### ISSUE THREAD

**Issue by CMCDragonkai** [aio-libs/aiojobs#252] opened 2021-04-29 05:02 UTC
I've noticed that sometimes when I have done `await scheduler.close()`, there's an `asyncio.CancelledError` thrown.

This isn't documented at all.

But it sometimes doesn't happen either.

What would cause `await scheduler.close()` to throw that error?

So far I've resolved to do:

```
try:
    await scheduler.close()
except asyncio.CancelledError:
    pass
```

This is happening even for schedulers that have no jobs whatsoever.

What's weird is that I try to reproduce with a simple script but it doesn't work:

```py
import asyncio
import aiojobs

async def f ():
    scheduler = await aiojobs.create_scheduler()
    try:
        await scheduler.close()
        print('closed')
    except Exception as e:
        print(e.__class__.__name__)

def main():
    loop = asyncio.get_event_loop()
    loop.run_until_complete(f())
    print('done')

main()
```

**Comment by CMCDragonkai** [comment] 2021-04-29 05:04
One situation where this is happening involves aiohttp:

```py
    async def start_scheduler(app):
        logger.info("Starting Scheduler")
        # this allows the usage of aiojobs get_scheduler_from_* functions
        app["AIOJOBS_SCHEDULER"] = await aiojobs.create_scheduler()
        logger.info("Started Scheduler")

    async def stop_scheduler(app):
        logger.info("Stopping Scheduler")
        try:
            await app["AIOJOBS_SCHEDULER"].close()
        except asyncio.CancelledError:
            pass
        logger.info("Stopped Scheduler")
```

Later I put it on the app itself:

```py
    container["app"].on_startup.append(start_scheduler)
    container["app"].on_shutdown.append(stop_scheduler)
```

Even when no jobs have been scheduled. I start the aiohttp server and just shut it down right afterwards I can see that the error is thrown.

**Comment by CMCDragonkai** [comment] 2021-04-29 05:07
Also not sure about the difference between `on_cleanup` and `on_shutdown`?

**Comment by evgenymarkov** [comment] 2021-11-19 16:47
Seeing the same issue when using aiohttp and aiojobs at the same time. I have prepared an example on which the problem is easily reproduced: https://github.com/evgenymarkov/aiojobs-close-bug.

The error "Cancellederror" occurs in the code during the closing of JobScheduler:

```python
try:
    await self._job_scheduler.close()
except asyncio.CancelledError:
    # See: https://github.com/aio-libs/aiojobs/issues/252
    logging.exception("Failed to dispose job scheduler")
else:
    logging.info("Background job scheduler has been disposed")
```

```
======== Running on http://127.0.0.1:2000 ========
(Press CTRL+C to quit)
^CINFO:root:HTTP server has been interrupted
ERROR:root:Failed to dispose job scheduler
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.9/3.9.8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/homebrew/Cellar/python@3.9/3.9.8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "/opt/homebrew/Cellar/python@3.9/3.9.8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 596, in run_forever
    self._run_once()
  File "/opt/homebrew/Cellar/python@3.9/3.9.8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 1890, in _run_once
    handle._run()
  File "/opt/homebrew/Cellar/python@3.9/3.9.8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/opt/homebrew/lib/python3.9/site-packages/aiohttp/web_runner.py", line 36, in _raise_graceful_exit
    raise GracefulExit()
aiohttp.web_runner.GracefulExit

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.9/site-packages/aiojobs/_scheduler.py", line 129, in _wait_failed
    task = await self._failed_tasks.get()
  File "/opt/homebrew/Cellar/python@3.9/3.9.8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/queues.py", line 166, in get
    await getter
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/evgenymarkov/Personal/aiojobs-close-bug/main.py", line 48, in dispose
    await self._job_scheduler.close()
  File "/opt/homebrew/lib/python3.9/site-packages/aiojobs/_scheduler.py", line 95, in close
    await self._failed_task
asyncio.exceptions.CancelledError
```

**Comment by JohnEskimSmith** [comment] 2022-03-17 21:32
problems with aiohttp and aiojobs are solved by passing the loop to web.run_app.
Example: 
loop = asyncio.get_event_loop()
...
app = loop.run_until_complete(c_init)
web.run_app(app, sock=sock, access_log=logger, loop=loop)
...

**Comment by Dreamsorcerer** [comment] 2022-10-15 17:36
Looks like some bad uses of asyncio/aiohttp which is causing the task to get cancelled before `scheduler.close()` is run. These look like bugs in user code, not aiojobs.


> problems with aiohttp and aiojobs are solved by passing the loop to web.run_app.

The loop argument should not be used, or any of those low-level asyncio functions, for a typical application. Instead you should create and shutdown the scheduler as part of the application lifecycle.



> Seeing the same issue when using aiohttp and aiojobs at the same time. I have prepared an example on which the problem is easily reproduced: https://github.com/evgenymarkov/aiojobs-close-bug.

This code is closer, but still misses the application lifecycle. Create and shutdown the scheduler using a cleanup context: https://docs.aiohttp.org/en/stable/web_advanced.html#cleanup-context
Don't use the private `_run_app()` function, and instead use `run_app()` in place of `asyncio.run()`. See the documentation for additional examples of how to run processes etc. alongside an app: https://docs.aiohttp.org/en/stable/web_advanced.html#complex-applications

**Closed by Dreamsorcerer** 2022-10-15 17:36 UTC
