### ISSUE TITLE
All jobs immediately canceled without waiting for any timeout

### ISSUE THREAD

**Issue by djmarsel** [aio-libs/aiojobs#384] opened 2023-01-11 17:41 UTC
It is not possible to perform a graceful shutdown since version v1.1.0 after some change, when all jobs immediately canceled without waiting for close_timeout.

Look at this line:
https://github.com/aio-libs/aiojobs/blob/v1.1.0/aiojobs/_job.py#L93

This behaviour appears after the commit is applied
https://github.com/aio-libs/aiojobs/commit/bd17e3312a759234b8f41503d78fefe04558dfd1
in release version 1.1.0

**Comment by Dreamsorcerer** [comment] 2023-01-11 18:35
Please provide a reproducer that demonstrates the issue.

The linked change is correct, the `.done()` call does nothing. The `.cancel()` call makes the same call internally:
https://github.com/python/cpython/blob/main/Lib/asyncio/tasks.py#L214

**Comment by Dreamsorcerer** [comment] 2023-01-11 18:53
> when all jobs immediately canceled without waiting for close_timeout.

This sounds like the expected behaviour in all releases, nothing to do with v1.1...

I think this is actually just a duplicate of https://github.com/aio-libs/aiojobs/issues/48#issuecomment-1272625139
Feel free to make a PR to introduce the `wait_and_close()` method.

**Closed by Dreamsorcerer** 2023-01-11 18:53 UTC

**Comment by djmarsel** [comment] 2023-01-12 09:45
I am using aiojobs.aiohttp.setup(), which should ensure that all tasks will be closed after waiting some timeout when shutting down.
But on clenuap the scheduler.close() method is called, which cancels all tasksusing _job.cancel().
So if any requests to the server was interrupted by the client, these jobs are immediately interrupted on shutdowning. This leads to data loss and does not behave as expected for me.
Thanks.

**Comment by Dreamsorcerer** [comment] 2023-01-12 18:09
Yes, see #48.. Again, feel free to start working on that solution if you have some time.

For that specific case, I'd rather fix it in aiohttp, but haven't had the time to look at it yet.
